/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b3A98xAuzjmqz7n1KjRySq
// Component: NaZNs0zYERHd
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: b3A98xAuzjmqz7n1KjRySq/projectcss
import sty from "./PlasmicTermsOfService.module.css"; // plasmic-import: NaZNs0zYERHd/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: emwrKvxc7A0S/icon

createPlasmicElementProxy;

export const PlasmicTermsOfService__VariantProps = new Array();

export const PlasmicTermsOfService__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTermsOfService__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <IconIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            </section>
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {"Terms of Service for Aloop"}
            </h1>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mgTIb
              )}
            >
              {""}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hNjhv
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    'Effective Date: April 3, 2025\n\nWelcome to Aloop. These Terms of Service ("Terms") govern your use of our mobile messaging app (the "Service"). By using the Service, you agree to these Terms. If you don\u2019t agree, please don\u2019t use the app.\n\n'
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"\u26a0\ufe0f Beta Disclaimer"}
                </span>
                <React.Fragment>
                  {"\nAloop is currently in beta. This means:\n"}
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__mjZ0
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__cqLL
                      )}
                    >
                      {
                        "Features may change, break, or be removed without notice."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__zNw6M
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__hoAwV
                      )}
                    >
                      {"Data may not be saved or delivered reliably."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__h3Gj
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__psxsg
                      )}
                    >
                      {"Bugs, errors, or interruptions may occur at any time."}
                    </li>
                  </ul>
                }
                <React.Fragment>
                  {
                    "\nBy using this beta version, you understand that the app is not final, and you use it entirely at your own risk. We offer no guarantees or warranties. Things may break.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"1. Who Can Use the App"}
                </span>
                <React.Fragment>{"\nTo use Aloop, you must:\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__q79Hk
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__snJo7
                      )}
                    >
                      {
                        "Be at least 18 years old (or the legal minimum in your country)."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__gVn62
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__rqdMk
                      )}
                    >
                      {"Use your own phone number or identity."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__iNaK
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___90Zqs
                      )}
                    >
                      {"Agree to follow these Terms."}
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"2. What You Can\u2019t Do"}
                </span>
                <React.Fragment>{"\nYou agree not to:\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__sl9Cj
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__bfOK
                      )}
                    >
                      {
                        "Use the app for any illegal, harmful, or abusive activities."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__pyvqn
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___85Pxb
                      )}
                    >
                      {"Impersonate others or provide false information."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__hEut1
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__zpAuG
                      )}
                    >
                      {"Spam users or send unsolicited messages."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__yGSfK
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li___1NGg5
                      )}
                    >
                      {"Reverse-engineer, hack, or tamper with the app."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__o9AaR
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__xpUa
                      )}
                    >
                      {"Interfere with our servers, networks, or systems."}
                    </li>
                  </ul>
                }
                <React.Fragment>
                  {
                    "\nWe reserve the right to suspend or terminate your account if you violate these rules.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"3. Your Content"}
                </span>
                <React.Fragment>
                  {
                    "\nYou\u2019re responsible for any messages or content you send using the app.\nWe don\u2019t claim ownership of your content. But you grant us permission to process and transmit it as needed to operate the app \u2014 like syncing, notifications, and delivery.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"4. Privacy"}
                </span>
                <React.Fragment>
                  {
                    "\nWe respect your privacy. Please read our Privacy Policy to understand what data we collect and how we use it.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"5. Availability"}
                </span>
                <React.Fragment>
                  {"\nWe try to keep the app running smoothly, but:\n"}
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__dvG2L
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__zOrv
                      )}
                    >
                      {"We can\u2019t guarantee uptime or performance."}
                    </li>
                  </ul>
                }
                <React.Fragment>{""}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__iMMxi
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__oyQcs
                      )}
                    >
                      {"Features may be updated, changed, or removed anytime."}
                    </li>
                  </ul>
                }
                <React.Fragment>
                  {
                    "\nYou use the Service as-is and at your own discretion.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"6. Limitation of Liability"}
                </span>
                <React.Fragment>
                  {"\nTo the fullest extent allowed by law:\n"}
                </React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__xVlOm
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__u9MUj
                      )}
                    >
                      {
                        "Aloop, its team, and affiliates are not liable for any direct, indirect, incidental, or consequential damages \u2014 including lost data, profits, or privacy \u2014 resulting from your use of the app."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__aWx8S
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__iYIj
                      )}
                    >
                      {
                        "You understand and agree that this is a beta app, and that you will not hold us responsible for anything that goes wrong."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n"}</React.Fragment>
                {
                  <ul
                    className={classNames(
                      projectcss.all,
                      projectcss.ul,
                      sty.ul__nZiMa
                    )}
                  >
                    <li
                      className={classNames(
                        projectcss.all,
                        projectcss.li,
                        projectcss.__wab_text,
                        sty.li__o6TFk
                      )}
                    >
                      {
                        "You waive your right to take legal action against us for any issues related to this beta experience, whether it's bugs, outages, data loss, or any other problem."
                      }
                    </li>
                  </ul>
                }
                <React.Fragment>{"\n\n\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"7. Termination"}
                </span>
                <React.Fragment>
                  {
                    "\nWe may suspend or remove your access to the app if you violate these Terms.\nYou can stop using the app at any time. We may also stop offering the Service without notice.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"8. Changes to These Terms"}
                </span>
                <React.Fragment>
                  {
                    "\nWe may update these Terms from time to time. If we do, we\u2019ll do our best to notify you. Continued use of the app means you accept the updated Terms.\n\n"
                  }
                </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700 }}
                >
                  {"9. Contact"}
                </span>
                <React.Fragment>
                  {"\nGot questions? Reach us at contact@aloopid.com\n\n\n"}
                </React.Fragment>
              </React.Fragment>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "section", "svg", "h1"],
  freeBox: ["freeBox", "section", "svg", "h1"],
  section: ["section", "svg"],
  svg: ["svg"],
  h1: ["h1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTermsOfService__ArgProps,
          internalVariantPropNames: PlasmicTermsOfService__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTermsOfService__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTermsOfService";
  } else {
    func.displayName = `PlasmicTermsOfService.${nodeName}`;
  }
  return func;
}

export const PlasmicTermsOfService = Object.assign(
  // Top-level PlasmicTermsOfService renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    section: makeNodeComponent("section"),
    svg: makeNodeComponent("svg"),
    h1: makeNodeComponent("h1"),
    // Metadata about props expected for PlasmicTermsOfService
    internalVariantProps: PlasmicTermsOfService__VariantProps,
    internalArgProps: PlasmicTermsOfService__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTermsOfService;
/* prettier-ignore-end */
